import type { CountryDTO } from './dto/country.dto';

/**
 * Issuing countries and territories whose flags exist in flag-icons (ISO 3166-1 alpha-2).
 * Dropped: uninhabited / non-issuer (AQ, BV, HM, IO, TF, GS, UM, CP, DG) and org placeholders (UN, EU, XX).
 *
 * Priority model:
 * - 1–30: featured travel / rental markets (shown first).
 * - 100: everyone else, ordered A–Z by English name after the featured block.
 */

export const COUNTRIES_MVP: CountryDTO[] = [
  { code: 'US', name: 'United States', priority: 1 },
  { code: 'CA', name: 'Canada', priority: 2 },
  { code: 'GB', name: 'United Kingdom', priority: 3 },
  { code: 'AU', name: 'Australia', priority: 4 },
  { code: 'DE', name: 'Germany', priority: 5 },
  { code: 'FR', name: 'France', priority: 6 },
  { code: 'ES', name: 'Spain', priority: 7 },
  { code: 'IT', name: 'Italy', priority: 8 },
  { code: 'NL', name: 'Netherlands', priority: 9 },
  { code: 'CH', name: 'Switzerland', priority: 10 },
  { code: 'PL', name: 'Poland', priority: 11 },
  { code: 'SE', name: 'Sweden', priority: 12 },
  { code: 'NO', name: 'Norway', priority: 13 },
  { code: 'FI', name: 'Finland', priority: 14 },
  { code: 'AT', name: 'Austria', priority: 15 },
  { code: 'BE', name: 'Belgium', priority: 16 },
  { code: 'IE', name: 'Ireland', priority: 17 },
  { code: 'PT', name: 'Portugal', priority: 18 },
  { code: 'CZ', name: 'Czechia', priority: 19 },
  { code: 'RU', name: 'Russia', priority: 20 },
  { code: 'UA', name: 'Ukraine', priority: 21 },
  { code: 'TR', name: 'Türkiye', priority: 22 },
  { code: 'CN', name: 'China', priority: 23 },
  { code: 'JP', name: 'Japan', priority: 24 },
  { code: 'KR', name: 'South Korea', priority: 25 },
  { code: 'IN', name: 'India', priority: 26 },
  { code: 'BR', name: 'Brazil', priority: 27 },
  { code: 'MX', name: 'Mexico', priority: 28 },
  { code: 'AR', name: 'Argentina', priority: 29 },
  { code: 'ZA', name: 'South Africa', priority: 30 },
  { code: 'AF', name: 'Afghanistan', priority: 100 },
  { code: 'AX', name: 'Åland Islands', priority: 100 },
  { code: 'AL', name: 'Albania', priority: 100 },
  { code: 'DZ', name: 'Algeria', priority: 100 },
  { code: 'AS', name: 'American Samoa', priority: 100 },
  { code: 'AD', name: 'Andorra', priority: 100 },
  { code: 'AO', name: 'Angola', priority: 100 },
  { code: 'AI', name: 'Anguilla', priority: 100 },
  { code: 'AG', name: 'Antigua & Barbuda', priority: 100 },
  { code: 'AM', name: 'Armenia', priority: 100 },
  { code: 'AW', name: 'Aruba', priority: 100 },
  { code: 'AZ', name: 'Azerbaijan', priority: 100 },
  { code: 'BS', name: 'Bahamas', priority: 100 },
  { code: 'BH', name: 'Bahrain', priority: 100 },
  { code: 'BD', name: 'Bangladesh', priority: 100 },
  { code: 'BB', name: 'Barbados', priority: 100 },
  { code: 'BY', name: 'Belarus', priority: 100 },
  { code: 'BZ', name: 'Belize', priority: 100 },
  { code: 'BJ', name: 'Benin', priority: 100 },
  { code: 'BM', name: 'Bermuda', priority: 100 },
  { code: 'BT', name: 'Bhutan', priority: 100 },
  { code: 'BO', name: 'Bolivia', priority: 100 },
  { code: 'BA', name: 'Bosnia & Herzegovina', priority: 100 },
  { code: 'BW', name: 'Botswana', priority: 100 },
  { code: 'VG', name: 'British Virgin Islands', priority: 100 },
  { code: 'BN', name: 'Brunei', priority: 100 },
  { code: 'BG', name: 'Bulgaria', priority: 100 },
  { code: 'BF', name: 'Burkina Faso', priority: 100 },
  { code: 'BI', name: 'Burundi', priority: 100 },
  { code: 'KH', name: 'Cambodia', priority: 100 },
  { code: 'CM', name: 'Cameroon', priority: 100 },
  { code: 'IC', name: 'Canary Islands', priority: 100 },
  { code: 'CV', name: 'Cape Verde', priority: 100 },
  { code: 'BQ', name: 'Caribbean Netherlands', priority: 100 },
  { code: 'KY', name: 'Cayman Islands', priority: 100 },
  { code: 'CF', name: 'Central African Republic', priority: 100 },
  { code: 'TD', name: 'Chad', priority: 100 },
  { code: 'CL', name: 'Chile', priority: 100 },
  { code: 'CX', name: 'Christmas Island', priority: 100 },
  { code: 'CC', name: 'Cocos (Keeling) Islands', priority: 100 },
  { code: 'CO', name: 'Colombia', priority: 100 },
  { code: 'KM', name: 'Comoros', priority: 100 },
  { code: 'CG', name: 'Congo', priority: 100 },
  { code: 'CK', name: 'Cook Islands', priority: 100 },
  { code: 'CR', name: 'Costa Rica', priority: 100 },
  { code: 'CI', name: 'Côte d\'Ivoire', priority: 100 },
  { code: 'HR', name: 'Croatia', priority: 100 },
  { code: 'CU', name: 'Cuba', priority: 100 },
  { code: 'CW', name: 'Curaçao', priority: 100 },
  { code: 'CY', name: 'Cyprus', priority: 100 },
  { code: 'DK', name: 'Denmark', priority: 100 },
  { code: 'DJ', name: 'Djibouti', priority: 100 },
  { code: 'DM', name: 'Dominica', priority: 100 },
  { code: 'DO', name: 'Dominican Republic', priority: 100 },
  { code: 'CD', name: 'DR Congo', priority: 100 },
  { code: 'EC', name: 'Ecuador', priority: 100 },
  { code: 'EG', name: 'Egypt', priority: 100 },
  { code: 'SV', name: 'El Salvador', priority: 100 },
  { code: 'GQ', name: 'Equatorial Guinea', priority: 100 },
  { code: 'ER', name: 'Eritrea', priority: 100 },
  { code: 'EE', name: 'Estonia', priority: 100 },
  { code: 'SZ', name: 'Eswatini', priority: 100 },
  { code: 'ET', name: 'Ethiopia', priority: 100 },
  { code: 'FK', name: 'Falkland Islands', priority: 100 },
  { code: 'FO', name: 'Faroe Islands', priority: 100 },
  { code: 'FJ', name: 'Fiji', priority: 100 },
  { code: 'GF', name: 'French Guiana', priority: 100 },
  { code: 'PF', name: 'French Polynesia', priority: 100 },
  { code: 'GA', name: 'Gabon', priority: 100 },
  { code: 'GM', name: 'Gambia', priority: 100 },
  { code: 'GE', name: 'Georgia', priority: 100 },
  { code: 'GH', name: 'Ghana', priority: 100 },
  { code: 'GI', name: 'Gibraltar', priority: 100 },
  { code: 'GR', name: 'Greece', priority: 100 },
  { code: 'GL', name: 'Greenland', priority: 100 },
  { code: 'GD', name: 'Grenada', priority: 100 },
  { code: 'GP', name: 'Guadeloupe', priority: 100 },
  { code: 'GU', name: 'Guam', priority: 100 },
  { code: 'GT', name: 'Guatemala', priority: 100 },
  { code: 'GG', name: 'Guernsey', priority: 100 },
  { code: 'GN', name: 'Guinea', priority: 100 },
  { code: 'GW', name: 'Guinea-Bissau', priority: 100 },
  { code: 'GY', name: 'Guyana', priority: 100 },
  { code: 'HT', name: 'Haiti', priority: 100 },
  { code: 'HN', name: 'Honduras', priority: 100 },
  { code: 'HK', name: 'Hong Kong SAR China', priority: 100 },
  { code: 'HU', name: 'Hungary', priority: 100 },
  { code: 'IS', name: 'Iceland', priority: 100 },
  { code: 'ID', name: 'Indonesia', priority: 100 },
  { code: 'IR', name: 'Iran', priority: 100 },
  { code: 'IQ', name: 'Iraq', priority: 100 },
  { code: 'IM', name: 'Isle of Man', priority: 100 },
  { code: 'IL', name: 'Israel', priority: 100 },
  { code: 'JM', name: 'Jamaica', priority: 100 },
  { code: 'JE', name: 'Jersey', priority: 100 },
  { code: 'JO', name: 'Jordan', priority: 100 },
  { code: 'KZ', name: 'Kazakhstan', priority: 100 },
  { code: 'KE', name: 'Kenya', priority: 100 },
  { code: 'KI', name: 'Kiribati', priority: 100 },
  { code: 'XK', name: 'Kosovo', priority: 100 },
  { code: 'KW', name: 'Kuwait', priority: 100 },
  { code: 'KG', name: 'Kyrgyzstan', priority: 100 },
  { code: 'LA', name: 'Laos', priority: 100 },
  { code: 'LV', name: 'Latvia', priority: 100 },
  { code: 'LB', name: 'Lebanon', priority: 100 },
  { code: 'LS', name: 'Lesotho', priority: 100 },
  { code: 'LR', name: 'Liberia', priority: 100 },
  { code: 'LY', name: 'Libya', priority: 100 },
  { code: 'LI', name: 'Liechtenstein', priority: 100 },
  { code: 'LT', name: 'Lithuania', priority: 100 },
  { code: 'LU', name: 'Luxembourg', priority: 100 },
  { code: 'MO', name: 'Macao SAR China', priority: 100 },
  { code: 'MG', name: 'Madagascar', priority: 100 },
  { code: 'MW', name: 'Malawi', priority: 100 },
  { code: 'MY', name: 'Malaysia', priority: 100 },
  { code: 'MV', name: 'Maldives', priority: 100 },
  { code: 'ML', name: 'Mali', priority: 100 },
  { code: 'MT', name: 'Malta', priority: 100 },
  { code: 'MH', name: 'Marshall Islands', priority: 100 },
  { code: 'MQ', name: 'Martinique', priority: 100 },
  { code: 'MR', name: 'Mauritania', priority: 100 },
  { code: 'MU', name: 'Mauritius', priority: 100 },
  { code: 'YT', name: 'Mayotte', priority: 100 },
  { code: 'FM', name: 'Micronesia', priority: 100 },
  { code: 'MD', name: 'Moldova', priority: 100 },
  { code: 'MC', name: 'Monaco', priority: 100 },
  { code: 'MN', name: 'Mongolia', priority: 100 },
  { code: 'ME', name: 'Montenegro', priority: 100 },
  { code: 'MS', name: 'Montserrat', priority: 100 },
  { code: 'MA', name: 'Morocco', priority: 100 },
  { code: 'MZ', name: 'Mozambique', priority: 100 },
  { code: 'MM', name: 'Myanmar (Burma)', priority: 100 },
  { code: 'NA', name: 'Namibia', priority: 100 },
  { code: 'NR', name: 'Nauru', priority: 100 },
  { code: 'NP', name: 'Nepal', priority: 100 },
  { code: 'NC', name: 'New Caledonia', priority: 100 },
  { code: 'NZ', name: 'New Zealand', priority: 100 },
  { code: 'NI', name: 'Nicaragua', priority: 100 },
  { code: 'NE', name: 'Niger', priority: 100 },
  { code: 'NG', name: 'Nigeria', priority: 100 },
  { code: 'NU', name: 'Niue', priority: 100 },
  { code: 'NF', name: 'Norfolk Island', priority: 100 },
  { code: 'KP', name: 'North Korea', priority: 100 },
  { code: 'MK', name: 'North Macedonia', priority: 100 },
  { code: 'MP', name: 'Northern Mariana Islands', priority: 100 },
  { code: 'OM', name: 'Oman', priority: 100 },
  { code: 'PK', name: 'Pakistan', priority: 100 },
  { code: 'PW', name: 'Palau', priority: 100 },
  { code: 'PS', name: 'Palestine', priority: 100 },
  { code: 'PA', name: 'Panama', priority: 100 },
  { code: 'PG', name: 'Papua New Guinea', priority: 100 },
  { code: 'PY', name: 'Paraguay', priority: 100 },
  { code: 'PC', name: 'PC', priority: 100 },
  { code: 'PE', name: 'Peru', priority: 100 },
  { code: 'PH', name: 'Philippines', priority: 100 },
  { code: 'PN', name: 'Pitcairn Islands', priority: 100 },
  { code: 'PR', name: 'Puerto Rico', priority: 100 },
  { code: 'QA', name: 'Qatar', priority: 100 },
  { code: 'RE', name: 'Réunion', priority: 100 },
  { code: 'RO', name: 'Romania', priority: 100 },
  { code: 'RW', name: 'Rwanda', priority: 100 },
  { code: 'WS', name: 'Samoa', priority: 100 },
  { code: 'SM', name: 'San Marino', priority: 100 },
  { code: 'ST', name: 'São Tomé & Príncipe', priority: 100 },
  { code: 'SA', name: 'Saudi Arabia', priority: 100 },
  { code: 'SN', name: 'Senegal', priority: 100 },
  { code: 'RS', name: 'Serbia', priority: 100 },
  { code: 'SC', name: 'Seychelles', priority: 100 },
  { code: 'SL', name: 'Sierra Leone', priority: 100 },
  { code: 'SG', name: 'Singapore', priority: 100 },
  { code: 'SX', name: 'Sint Maarten', priority: 100 },
  { code: 'SK', name: 'Slovakia', priority: 100 },
  { code: 'SI', name: 'Slovenia', priority: 100 },
  { code: 'SB', name: 'Solomon Islands', priority: 100 },
  { code: 'SO', name: 'Somalia', priority: 100 },
  { code: 'SS', name: 'South Sudan', priority: 100 },
  { code: 'LK', name: 'Sri Lanka', priority: 100 },
  { code: 'BL', name: 'St. Barthélemy', priority: 100 },
  { code: 'SH', name: 'St. Helena', priority: 100 },
  { code: 'KN', name: 'St. Kitts & Nevis', priority: 100 },
  { code: 'LC', name: 'St. Lucia', priority: 100 },
  { code: 'MF', name: 'St. Martin', priority: 100 },
  { code: 'PM', name: 'St. Pierre & Miquelon', priority: 100 },
  { code: 'VC', name: 'St. Vincent & Grenadines', priority: 100 },
  { code: 'SD', name: 'Sudan', priority: 100 },
  { code: 'SR', name: 'Suriname', priority: 100 },
  { code: 'SJ', name: 'Svalbard & Jan Mayen', priority: 100 },
  { code: 'SY', name: 'Syria', priority: 100 },
  { code: 'TW', name: 'Taiwan', priority: 100 },
  { code: 'TJ', name: 'Tajikistan', priority: 100 },
  { code: 'TZ', name: 'Tanzania', priority: 100 },
  { code: 'TH', name: 'Thailand', priority: 100 },
  { code: 'TL', name: 'Timor-Leste', priority: 100 },
  { code: 'TG', name: 'Togo', priority: 100 },
  { code: 'TK', name: 'Tokelau', priority: 100 },
  { code: 'TO', name: 'Tonga', priority: 100 },
  { code: 'TT', name: 'Trinidad & Tobago', priority: 100 },
  { code: 'TN', name: 'Tunisia', priority: 100 },
  { code: 'TM', name: 'Turkmenistan', priority: 100 },
  { code: 'TC', name: 'Turks & Caicos Islands', priority: 100 },
  { code: 'TV', name: 'Tuvalu', priority: 100 },
  { code: 'VI', name: 'U.S. Virgin Islands', priority: 100 },
  { code: 'UG', name: 'Uganda', priority: 100 },
  { code: 'AE', name: 'United Arab Emirates', priority: 100 },
  { code: 'UY', name: 'Uruguay', priority: 100 },
  { code: 'UZ', name: 'Uzbekistan', priority: 100 },
  { code: 'VU', name: 'Vanuatu', priority: 100 },
  { code: 'VA', name: 'Vatican City', priority: 100 },
  { code: 'VE', name: 'Venezuela', priority: 100 },
  { code: 'VN', name: 'Vietnam', priority: 100 },
  { code: 'WF', name: 'Wallis & Futuna', priority: 100 },
  { code: 'EH', name: 'Western Sahara', priority: 100 },
  { code: 'YE', name: 'Yemen', priority: 100 },
  { code: 'ZM', name: 'Zambia', priority: 100 },
  { code: 'ZW', name: 'Zimbabwe', priority: 100 },
];
